server:
  port: 8443
  address: stevedev-local
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: XXX
    key-store-type: PKCS12
    key-alias: XXX

spring:
  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          forgerock:
            client-id: XXX
            client-secret: XXX
            client-authentication-method: client_secret_post
            client-name: ForgeRock
            provider: forgerock
            authorization-grant-type: authorization_code
            # Spring Security uses this as the redirect URI for the callback
            redirect-uri: "https://stevedev-local:8443/login/oauth2/code/forgerock"
            scope:
              - openid
              - profile
              - email
              # add any API scopes you need here (e.g., read write)
        provider:
          forgerock:
            # Use your ForgeRock OIDC issuer (AM)
            # Example: https://<your-fr-host>/am/oauth2/realms/<realm-name>
            issuer-uri: https://XXX:443/am/oauth2/alpha

# Optional: If used, this needs to be defined as one of the logout URIs on ForgeRock
app:
  post-logout-redirect-uri: "https://stevedev-local:8443/"

logging:
  level:
    "org.springframework.security.oauth2": DEBUG
    "org.springframework.web.client": DEBUG
    "org.springframework.http.client": DEBUG
